name: image-sr
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - blas
  - blosc
  - brotli
  - brotli-bin
  - brunsli
  - charls
  - dask-core
  - dbus
  - expat
  - fftw
  - flit-core
  - fontconfig
  - fonttools
  - imagecodecs
  - imageio
  - intel-openmp
  - jpeg
  - kiwisolver=1.4.2
  - krb5
  - locket
  - matplotlib
  - networkx
  - ninja
  - ninja-base
  - numpy
  - numpy-base
  - partd
  - pip
  - pycparser
  - pyparsing
  - python=3.10
  - pytorch=1.10.2
  - pywavelets
  - readline
  - scikit-image
  - scipy
  - sip
  - six
  - sqlite
  - tifffile
  - tk
  - toml
  - toolz
  - torchvision
  - typing-extensions
  - yaml=0.2.5
  - pip:
      - idna==3.4
      - pyyaml==6.0
      - requests
      - urllib3
      - opencv-python
      - oauthlib
      - hdf5storage
      - ninja
      - lmdb
      - requests
      - timm
      - einops
      - pillow
